### ISSUE TITLE
"autoboots last used option on IOSU reload" configurable?

### ISSUE THREAD

**Issue by wp2000x** [jan-hofmeier/minute_minute#1]
Hello,

can you maybe make the "autoboots last used option on IOSU reload" feature configurable via ini so that it can be switched off?
I have a wii u with a dead HDMI chip and this is the only way to see the image in minute and am forced to use an older version where this feature was not there yet.

Cheers

**Comment by jan-hofmeier** [comment]
It's implemented in the https://github.com/jan-hofmeier/stroopwafel/releases/tag/redseeprom-v1.1 release
