### ISSUE TITLE
Stuck on "jumping to IOS GO, GO, GO

### ISSUE THREAD

**Issue by rostomzer** [jan-hofmeier/minute_minute#3]
Everything looks fine (boot, backup, etc...)
When i selzct 3rd optionwhich is patch sd and boot ios (slc) it did some things and the last line says jumping to ios go go go and stays there forever!
https://cdn.discordapp.com/attachments/279783073497874442/1281320206764867779/rn_image_picker_lib_temp_ab31ea25-b3cd-4d09-88e1-c365fd3eaa14.jpg?ex=66db49ef&is=66d9f86f&hm=dff4930a172d5aac6479024f1636d960bf1ecd8474d212bb4683ae5a55bd260b&

**Comment by jan-hofmeier** [comment]
This isn't a minute problem. Either there is a problem with the plugins or the system

**Comment by rostomzer** [comment]
> This isn't a minute problem. Either there is a problem with the plugins or the system

Yes indeed i just did proceed with redNAND and everything is okay. Console is alive! Thanks for the clarification
